package com.aprianto.p13apiandroid.API_config.Barang;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

public class ModelBarang {
    /*
    ⚠ WARNING :
    - SESUAIKAN DENGAN OUTPUT PADA LOG JSON, masukan pada laman https://www.jsonschema2pojo.org/
     */

    // diambil dari class Hasil di web : https://www.jsonschema2pojo.org/
    @SerializedName("kode")
    @Expose
    private String kode;
    @SerializedName("nama")
    @Expose
    private String nama;
    @SerializedName("satuan")
    @Expose
    private String satuan;
    @SerializedName("hargabeli")
    @Expose
    private String hargabeli;
    @SerializedName("hargajual")
    @Expose
    private String hargajual;
    @SerializedName("diskon")
    @Expose
    private String diskon;

    // generated by alt + insert -> setter & getter
    public String getKode() {
        return kode;
    }

    public void setKode(String kode) {
        this.kode = kode;
    }

    public String getNama() {
        return nama;
    }

    public void setNama(String nama) {
        this.nama = nama;
    }

    public String getSatuan() {
        return satuan;
    }

    public void setSatuan(String satuan) {
        this.satuan = satuan;
    }

    public String getHargabeli() {
        return hargabeli;
    }

    public void setHargabeli(String hargabeli) {
        this.hargabeli = hargabeli;
    }

    public String getHargajual() {
        return hargajual;
    }

    public void setHargajual(String hargajual) {
        this.hargajual = hargajual;
    }

    public String getDiskon() {
        return diskon;
    }

    public void setDiskon(String diskon) {
        this.diskon = diskon;
    }
}
